version: '3.8'

services:
  app:
    build: .
    networks:
      - network
    ports:
      - 3000:3000

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - network
    ports:
      - 5432:5432

networks:
  network:
